version: '3'

networks:
  back-tier:

services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    links:
      - "backend:be"
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: backend
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    networks:
      - back-tier
    ports:
      - "5000:5000"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db:z
    networks:
      - back-tier
    ports:
      - "27017:27017"